from .base import CoreOpcode, opcode
from .dtypes import Code, Program, Ptr, Value


@opcode
def add(ptr: Ptr, value: Value) -> None: ...
@opcode
def input(ptr: Ptr) -> None: ...
@opcode
def output(ptr: Ptr) -> None: ...
@opcode
def loop(ptr: Ptr, program: Program[CoreOpcode]) -> None: ...
@opcode
def inject(ptr: Ptr, code: Code, exit: Ptr) -> None: ...
