from .base import opcode
from .dtypes import Code, Program, Ref, Value


@opcode
def add(ref: Ref, value: Value) -> None: ...
@opcode
def input(ref: Ref) -> None: ...
@opcode
def output(ref: Ref) -> None: ...
@opcode
def loop(ref: Ref, program: Program) -> None: ...
@opcode
def inject(ref: Ref, code: Code, exit: Ref) -> None: ...
