
from .base import opcode
from .dtypes import Ptr, Value, Program, Code


@opcode
def add(ptr: Ptr, value: Value) -> None: ...
@opcode
def input(ptr: Ptr) -> None: ...
@opcode
def output(ptr: Ptr) -> None: ...
@opcode
def loop(ptr: Ptr, program: Program) -> None: ...
@opcode
def inject(ptr: Ptr, code: Code, exit: Ptr) -> None: ...
