from typing import Any, overload

from quix.bootstrap.dtypes.const import UInt8
from quix.core.opcodes.base import CoreOpcode, opcode
from quix.core.opcodes.dtypes import CoreProgram

from .dtypes import Array, Cell, Const, Str, UCell, UDynamic, Unit, Wide


@overload
def add(left: Wide, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def add(left: UDynamic, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def add(left: Unit, right: Unit, target: Unit) -> CoreOpcode: ...
@overload
def add(left: UCell, right: Unit, target: Unit) -> CoreOpcode: ...
@opcode
def add(left: Wide | UDynamic | Unit | UCell, right: Wide | Unit, target: Wide | Unit) -> None: ...


@overload
def addc(left: Wide, right: Wide, target: Wide, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def addc(left: UDynamic, right: Wide, target: Wide, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def addc(left: Unit, right: Unit, target: Unit, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def addc(left: UCell, right: Unit, target: Unit, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@opcode
def addc(
    left: Wide | UDynamic | Unit | UCell, right: Wide | Unit, target: Wide | Unit, carries: tuple[Unit, ...]
) -> None: ...


@overload
def sub(left: Wide, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def sub(left: UDynamic, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def sub(left: Wide, right: UDynamic, target: Wide) -> CoreOpcode: ...
@overload
def sub(left: Unit, right: Unit, target: Unit) -> CoreOpcode: ...
@overload
def sub(left: UCell, right: Unit, target: Unit) -> CoreOpcode: ...
@overload
def sub(left: Unit, right: UCell, target: Unit) -> CoreOpcode: ...
@opcode
def sub(left: Wide | UDynamic | Unit | UCell, right: Wide | UDynamic | Unit | UCell, target: Wide | Unit) -> None: ...


@overload
def subc(left: Wide, right: Wide, target: Wide, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def subc(left: UDynamic, right: Wide, target: Wide, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def subc(left: Wide, right: UDynamic, target: Wide, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def subc(left: Unit, right: Unit, target: Unit, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def subc(left: UCell, right: Unit, target: Unit, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def subc(left: Unit, right: UCell, target: Unit, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@opcode
def subc(
    left: Wide | UDynamic | Unit | UCell,
    right: Wide | UDynamic | Unit | UCell,
    target: Wide | Unit,
    carries: tuple[Unit, ...],
) -> None: ...


@overload
def mul(left: Wide, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def mul(left: UDynamic, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def mul(left: Unit, right: Unit, target: Unit) -> CoreOpcode: ...
@overload
def mul(left: UCell, right: Unit, target: Unit) -> CoreOpcode: ...
@opcode
def mul(left: Wide | UDynamic | Unit | UCell, right: Wide | Unit, target: Wide | Unit) -> None: ...


@overload
def mulc(left: Wide, right: Wide, target: Wide, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def mulc(left: UDynamic, right: Wide, target: Wide, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def mulc(left: Unit, right: Unit, target: Unit, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@overload
def mulc(left: UCell, right: Unit, target: Unit, carries: tuple[Unit, ...]) -> CoreOpcode: ...
@opcode
def mulc(
    left: Wide | UDynamic | Unit | UCell, right: Wide | Unit, target: Wide | Unit, carries: tuple[Unit, ...]
) -> None: ...


@overload
def div(left: Wide, right: Wide, quot: None, rem: Wide) -> CoreOpcode: ...
@overload
def div(left: Wide, right: Wide, quot: Wide, rem: None) -> CoreOpcode: ...
@overload
def div(left: Wide, right: Wide, quot: Wide, rem: Wide) -> CoreOpcode: ...
@overload
def div(left: UDynamic, right: Wide, quot: None, rem: Wide) -> CoreOpcode: ...
@overload
def div(left: UDynamic, right: Wide, quot: Wide, rem: None) -> CoreOpcode: ...
@overload
def div(left: UDynamic, right: Wide, quot: Wide, rem: Wide) -> CoreOpcode: ...
@overload
def div(left: Wide, right: UDynamic, quot: None, rem: Wide) -> CoreOpcode: ...
@overload
def div(left: Wide, right: UDynamic, quot: Wide, rem: None) -> CoreOpcode: ...
@overload
def div(left: Wide, right: UDynamic, quot: Wide, rem: Wide) -> CoreOpcode: ...
@overload
def div(left: Unit, right: Unit, quot: None, rem: Unit) -> CoreOpcode: ...
@overload
def div(left: Unit, right: Unit, quot: Unit, rem: None) -> CoreOpcode: ...
@overload
def div(left: Unit, right: Unit, quot: Unit, rem: Unit) -> CoreOpcode: ...
@overload
def div(left: UCell, right: Unit, quot: None, rem: Unit) -> CoreOpcode: ...
@overload
def div(left: UCell, right: Unit, quot: Unit, rem: None) -> CoreOpcode: ...
@overload
def div(left: UCell, right: Unit, quot: Unit, rem: Unit) -> CoreOpcode: ...
@overload
def div(left: Unit, right: UCell, quot: None, rem: Unit) -> CoreOpcode: ...
@overload
def div(left: Unit, right: UCell, quot: Unit, rem: None) -> CoreOpcode: ...
@overload
def div(left: Unit, right: UCell, quot: Unit, rem: Unit) -> CoreOpcode: ...
@opcode
def div(
    left: Wide | UDynamic | Unit | UCell,
    right: Wide | UDynamic | Unit | UCell,
    quot: Wide | Unit | None,
    rem: Wide | Unit | None,
) -> None: ...


@overload
def exec_eq(left: Unit, right: Unit, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_eq(left: UInt8, right: Unit, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_eq(left: Wide, right: Wide, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_eq(left: UDynamic, right: Wide, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@opcode
def exec_eq(left: Unit | Wide | UInt8 | UDynamic, right: Unit | Wide, if_: CoreProgram, else_: CoreProgram) -> None: ...


@overload
def exec_neq(left: Unit, right: Unit, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_neq(left: UInt8, right: Unit, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_neq(left: Wide, right: Wide, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_neq(left: UDynamic, right: Wide, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@opcode
def exec_neq(
    left: Unit | Wide | UInt8 | UDynamic, right: Unit | Wide, if_: CoreProgram, else_: CoreProgram
) -> None: ...


@overload
def exec_z(left: Unit, right: Unit, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_z(left: UInt8, right: Unit, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_z(left: Wide, right: Wide, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_z(left: UDynamic, right: Wide, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@opcode
def exec_z(left: Unit | Wide | UInt8 | UDynamic, right: Unit | Wide, if_: CoreProgram, else_: CoreProgram) -> None: ...


@overload
def exec_geu(left: Unit, right: Unit, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_geu(left: UInt8, right: Unit, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_geu(left: Unit, right: UInt8, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_geu(left: Wide, right: Wide, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_geu(left: UDynamic, right: Wide, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_geu(left: Wide, right: UDynamic, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@opcode
def exec_geu(
    left: Unit | Wide | UInt8 | UDynamic, right: Unit | Wide | UInt8 | UDynamic, if_: CoreProgram, else_: CoreProgram
) -> None: ...


@overload
def exec_ge(left: Unit, right: Unit, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_ge(left: UInt8, right: Unit, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_ge(left: Unit, right: UInt8, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_ge(left: Wide, right: Wide, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_ge(left: UDynamic, right: Wide, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@overload
def exec_ge(left: Wide, right: UDynamic, if_: CoreProgram, else_: CoreProgram) -> CoreOpcode: ...
@opcode
def exec_ge(
    left: Unit | Wide | UInt8 | UDynamic, right: Unit | Wide | UInt8 | UDynamic, if_: CoreProgram, else_: CoreProgram
) -> None: ...


@overload
def and_(left: Wide, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def and_(left: UDynamic, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def and_(left: Unit, right: Unit, target: Unit) -> CoreOpcode: ...
@overload
def and_(left: UCell, right: Unit, target: Unit) -> CoreOpcode: ...
@opcode
def and_(left: Wide | UDynamic | Unit | UCell, right: Wide | Unit, target: Wide | Unit) -> None: ...


@overload
def or_(left: Wide, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def or_(left: UDynamic, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def or_(left: Unit, right: Unit, target: Unit) -> CoreOpcode: ...
@overload
def or_(left: UCell, right: Unit, target: Unit) -> CoreOpcode: ...
@opcode
def or_(left: Wide | UDynamic | Unit | UCell, right: Wide | Unit, target: Wide | Unit) -> None: ...


@overload
def xor(left: Wide, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def xor(left: UDynamic, right: Wide, target: Wide) -> CoreOpcode: ...
@overload
def xor(left: Unit, right: Unit, target: Unit) -> CoreOpcode: ...
@overload
def xor(left: UCell, right: Unit, target: Unit) -> CoreOpcode: ...
@opcode
def xor(left: Wide | UDynamic | Unit | UCell, right: Wide | Unit, target: Wide | Unit) -> None: ...


@overload
def not_(left: Wide, target: Wide) -> CoreOpcode: ...
@overload
def not_(left: Unit, target: Unit) -> CoreOpcode: ...
@opcode
def not_(left: Wide | Unit, target: Wide | Unit) -> None: ...


@opcode
def alloc(left: Wide | Unit | Array) -> None: ...
@opcode
def free(left: Wide | Unit | Array) -> None: ...


@opcode
def load(array: Array, index: Wide | Unit | UCell | UDynamic, value: UCell | UDynamic | Wide | Unit) -> None: ...
@opcode
def store(array: Array, index: Wide | Unit | UCell | UDynamic, target: Wide | Unit) -> None: ...


@overload
def switch(left: Wide, branches: dict[UDynamic, CoreProgram]) -> CoreOpcode: ...
@overload
def switch(left: Unit, branches: dict[UCell, CoreProgram]) -> CoreOpcode: ...
@opcode
def switch(left: Wide | Unit, branches: dict[UDynamic, CoreProgram] | dict[UCell, CoreProgram]) -> None: ...


@opcode
def loop(left: Wide | Unit, body: CoreProgram) -> None: ...


@opcode
def comment(left: str) -> None: ...


@opcode
def clear(left: Unit | Wide | Array) -> None: ...


@overload
def assign(left: Array | UDynamic | Wide, target: Array) -> CoreOpcode: ...
@overload
def assign(left: Wide | UDynamic | Array, target: Wide) -> CoreOpcode: ...
@overload
def assign(left: Unit | UCell, target: Unit) -> CoreOpcode: ...
@opcode
def assign(left: Unit | Wide | Array | UCell | UDynamic, target: Unit | Wide | Array) -> None: ...


@opcode
def output(*args: Array | Wide | UCell | UDynamic | Unit | Str | Const[Any]) -> None: ...


@opcode
def input(*to: Array | Wide | Unit, end: Unit | None = None) -> None: ...


@opcode
def move(left: Unit, target: dict[Unit, Cell]) -> None: ...


@opcode
def movec(left: Unit, target: dict[Unit, Cell], carries: dict[Unit, tuple[Unit, ...]]) -> None: ...
